### ISSUE TITLE
readme clarifications

### ISSUE THREAD

**Issue by danbjoseph** [smart-facility/opendronemap-ecs#10]
When setting up the launch configuration:
- In step 5, "needs to be the same as the security group used at step 1" is referencing what?

When creating the autoscaling group: 
- In sep 1, does the `Network` default of `Launch into EC2-Classic` work?
- In step 1, what should be chosen for `Availability Zone(s)`?
- In step 2, does the maximum size just affect the total number of concurrent project folders that can be processed at once?
- In step 2, if using the `Average CPU Utilization` metric, what is a suggested `Target value`?

In [odm-task-definition.json](https://github.com/OpenDroneMap/opendronemap-ecs/blob/master/odm-task-definition.json):
- In `containerDefinitions`, what is `name`?
- In `containerDefinitions`, what is `image`?

**Comment by matthewberryman** [comment]
@danbjoseph Your first point about the extra "needs to be the same as the security group used at step 1" is superfluous now—it's a carryover from when I was using EFS (no longer used) and the security group needed to be the same so that the instances could access the EFS. Just ignore that, I will remove that wording and add some other notes around security group requirements, along with addressing your other points in a fix to come. Note that the step numbering will change per #13.
